### ISSUE TITLE
Ошибка типов ("unsupported operand")

### ISSUE THREAD

**Issue by Azazel-h** [kewldan/AAIO#1]
Неактуальны требования к версии Python.

При запуске на 3.9 -- `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

Бинарный оператор | был разрешен к использованию в тайпхинтах в **версии 3.10**
Вот сылка на PEP (https://peps.python.org/pep-0604/)

Можно заменить на Union / Optional или просто обновить **требуемую** версию Python :)

**Comment by kewldan** [comment]
Добрый день, поправил все тайпхинты и протестировал лично на 3.7.9 и 3.12.1, теперь всё работает корректно. Версия задеплоена при релизе [v1.2.5](https://pypi.org/project/aaio/1.2.5/)

Спасибо за то, что сообщили
