### ISSUE TITLE
сreate_payment не использует self._base_url

### ISSUE THREAD

**Issue by Azazel-h** [kewldan/AAIO#2]
В связи с проблемами основного домена aaio.io попытался заменить на их зеркало, но заметил, что функция создания платежа не использует кастомный атрибут класса клиента `aaio.AAIO` (`base_url`)

```python
return f'https://aaio.io/merchant/pay?' + urlencode({k: v for k, v in params.items() if v is not None})
```

_Скорее всего потребуется заменить в форматной строке основную часть URL на `self._base_url`_

**Comment by kewldan** [comment]
Добрый день, вижу, в следующем релизе поправлю 🙌

**Comment by Azazel-h** [comment]
Ждем релиз :)
