### ISSUE TITLE
Будет ли добавлена информация о коммисии? 

### ISSUE THREAD

**Issue by Whom-m0rty** [kewldan/AAIO#9]
"commission_percent": 3, // Общий процент комиссии
"commission_user_percent": 3, // Процент комиссии на покупателе
"commission_merchant_percent": 0, // Процент комиссии на магазине
"commission_type": "0:100" // Процентное соотношение комиссии в формате "Комиссия магазина:Комиссия покупателя"
 
 
 https://wiki.aaio.so/api/dostupnye-metody-dlya-sozdaniya-zakaza

**Comment by kewldan** [comment]
Добавлено в [v1.4.2](https://github.com/kewldan/AAIO/releases/tag/v1.4.2)
